default: &default
  general_event: 4
  med_prof_ref: 4
  merch: 3
  social: 3
  fundraiser: 3
  volunteer: 3
  referral: 1
  opp: 1
  smedia: 1
  reset_date: 2022-04-15 18:54:30.042912

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default